language: java

os: linux

dist: xenial

services:
  - docker

jdk:
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14

jobs:
  include:
    - jdk: openjdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

install: true

script:
  - mvn verify
  - docker run -it --rm maven-jlink-docker-example

cache:
  directories:
    - '$HOME/.m2/repository'
